version: '3.8'
services:
  polynote-api:
    image: asgarovfarhad/polynote-api:1.0.0
    container_name: polynote-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_PASSWORD=
      - DB_USER=root
      - DB_NAME=polynote
      - DB_HOST=
      - DB_PORT=3306
      - APP_CORS=*
      - APP_PORT=8000
      - API_VERSION=1
      - APP_VERSION=development
      - PRIVATE_KEY=
      - ENCRYPTION_KEY=[]
    platform: linux/amd64
    restart: always
